const fs = require('fs');
const path = require('path');
const readline = require('readline');
const ARGS = process.argv.slice(2); 
const PLATFORM = ARGS[0];
const COMMAND = ARGS[0]; 
const TARGET_NAME = ARGS[1];
const APP_JS_PATH = path.join(__dirname, '../src/App.js');
const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const BLUE = '\x1b[36m';
const YELLOW = '\x1b[33m';
const RESET = '\x1b[0m';

// Template Fleetbo JS
const getWebTemplate = (pageName) => `import React from 'react';
//import { fleetboDB } from '@fleetbo';
import { ArrowLeftCircle } from 'lucide-react';
import { Box, Lock, Unlock, Coins, AlertCircle, RefreshCw, ShieldCheck } from 'lucide-react';

const ${pageName}Header = ({ onBack }) => (
    <header className='navbar ps-3 pt-3'>
        <div>
            <button onClick={onBack} className="btn-header text-success fs-5 fw-bold d-flex align-items-center">
                <ArrowLeftCircle /> <span className='ms-3'>${pageName}</span>
            </button>
        </div>
    </header>
);

const ${pageName} = () => {
    return (
        <>
            <PageConfig navbar="none" />
            <${pageName}Header onBack={() => Fleetbo.back()} />
            <div className="p-3 fade-in">
                <div className="text-center mt-5">
                    <h3 className="text-secondary">${pageName}</h3>
                    <p className="text-muted small">Generated by Fleetbo CLI</p>
                </div>
            </div>
        </>
    );
};

export default ${pageName};
`;

const injectIntoAppJs = (pageName, importPath, routePath) => {
    if (!fs.existsSync(APP_JS_PATH)) return false;
    let content = fs.readFileSync(APP_JS_PATH, 'utf8');
    if (!content.includes('// FLEETBO_IMPORTS') || (!content.includes('// FLEETBO_ROUTES') && !content.includes('{/* FLEETBO_ROUTES */}'))) {
        console.log(`${YELLOW}⚠️  Anchors not found in App.js. Skipping auto-wiring.${RESET}`);
        return false;
    }
    const cleanImport = importPath ? `/${importPath}` : '';
    const importLine = `import ${pageName} from './app${cleanImport}/${pageName}';`; 
    const routeLine = `<Route path="/${routePath}" element={<${pageName} />} />`;
    let injected = false;
    if (!content.includes(importLine)) {
        content = content.replace('// FLEETBO_IMPORTS', `${importLine}\n// FLEETBO_IMPORTS`);
        injected = true;
    }
    if (!content.includes(routeLine)) {
        const anchor = content.includes('{/* FLEETBO_ROUTES */}') ? '{/* FLEETBO_ROUTES */}' : '// FLEETBO_ROUTES';
        content = content.replace(anchor, `${routeLine}\n        ${anchor}`);
        injected = true;
    }
    if (injected) fs.writeFileSync(APP_JS_PATH, content);
    return injected;
};

const runWebGenerator = (inputPath) => {
    if (!inputPath) {
        askNameAndRun('Enter Page Path (e.g. admin/Settings):', runWebGenerator);
        return;
    }
    const parts = inputPath.split(/[/\\]/); 
    const rawName = parts.pop(); 
    const subDir = parts.join('/'); 
    const pageName = rawName.charAt(0).toUpperCase() + rawName.slice(1);
    const baseDir = path.join(__dirname, '../src/app');
    const targetDir = path.join(baseDir, subDir);
    const filePath = path.join(targetDir, `${pageName}.jsx`);

    if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });
    if (fs.existsSync(filePath)) {
        console.log(`${RED}  Error: Page "${pageName}" already exists!${RESET}`);
        process.exit(1);
    }

    fs.writeFileSync(filePath, getWebTemplate(pageName));
    const routePath = subDir ? `${subDir}/${pageName.toLowerCase()}` : `${pageName.toLowerCase()}`;
    const injected = injectIntoAppJs(pageName, subDir, routePath);
    console.log(`
       ${GREEN} FLEETBO WEB PAGE GENERATED${RESET}
       ${BLUE}src/app/${subDir ? subDir + '/' : ''}${pageName}.jsx${RESET}`);
    if (injected) {
        console.log(` App.js updated: Route /${routePath}`);
    }
};
const askNameAndRun = (question, callback) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    rl.question(`${BLUE}🧬 ${question} ${RESET}`, (n) => { 
        if(n) callback(n); 
        rl.close(); 
    });
};
const main = () => {
    if (COMMAND === 'page' || COMMAND === 'g') {
        runWebGenerator(TARGET_NAME); 
    } else {
        console.log(`
            ${BLUE}🧬 FLEETBO CLI (PILOT ONLY)${RESET}
            -------------------
            Usage:
            ${GREEN}npm run fleetbo page [Name]${RESET}      (Create Fleetbo JS Page)
            ${YELLOW}Note: Use "npm run fleetbo alex" for native infrastructure power modules.${RESET}
        `);
    }
};
main();
